# broker集群地址
server.address = 114.115.151.3:9092
# 业务主题列表
#bus.topic.list = log:klog_env_test
bus.topic.list = log:klog_env_prod

################### 已创建主题 ##################
# 日志相关
# 生产 klog_env_prod --replication-factor 3 --partitions 3
# 测试 klog_env_test --replication-factor 3 --partitions 3