// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Connection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * An application can implement this interface to receive notifications when
 * a connection closes or receives a heartbeat message.
 *
 * @see Connection#setCallback
 *
 **/
public interface _ConnectionCallbackOperationsNC
{
    /**
     * This method is called by the the connection when a heartbeat is
     * received from the peer.
     *
     **/
    void heartbeat(Connection con);

    /**
     * This method is called by the the connection when the connection
     * is closed.
     *
     **/
    void closed(Connection con);
}
