// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Connection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

public enum ACMClose
{
    
    CloseOff(0),
    
    CloseOnIdle(1),
    
    CloseOnInvocation(2),
    
    CloseOnInvocationAndIdle(3),
    
    CloseOnIdleForceful(4);

    public int
    value()
    {
        return __value;
    }

    public static ACMClose
    valueOf(int __v)
    {
        switch(__v)
        {
        case 0:
            return CloseOff;
        case 1:
            return CloseOnIdle;
        case 2:
            return CloseOnInvocation;
        case 3:
            return CloseOnInvocationAndIdle;
        case 4:
            return CloseOnIdleForceful;
        }
        return null;
    }

    private
    ACMClose(int __v)
    {
        __value = __v;
    }

    private final int __value;
}
