// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Get the router's server proxy, i.e., the proxy to use for
 * forwarding requests from the server to the router.
 * 
 **/

public abstract class Callback_Router_getServerProxy
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<Ice.ObjectPrx>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        RouterPrxHelper.__getServerProxy_completed(this, __result);
    }
}
