// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Router.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Get the router proxy implemented by the process hosting this
 * finder object. The proxy might point to several replicas.
 * 
 **/

public abstract class Callback_RouterFinder_getRouter
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<Ice.RouterPrx>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        RouterFinderPrxHelper.__getRouter_completed(this, __result);
    }
}
