// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Locator.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Find an adapter by id and return a proxy that contains
 * its endpoints.
 * 
 **/

public abstract class Callback_Locator_findAdapterById
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1UE<Ice.ObjectPrx>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        LocatorPrxHelper.__findAdapterById_completed(this, __result);
    }
}
