// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `RemoteLogger.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Log a {@link LogMessage}. Note that log may be called by {@link LoggerAdmin}
 * before {@link #init}.
 * 
 **/

public abstract class Callback_RemoteLogger_log extends Ice.OnewayCallback
{
}
