// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `PropertiesAdmin.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Get all properties whose keys begin with <em>prefix</em>. If
 * <em>prefix</em> is an empty string then all properties are returned.
 * 
 **/

public abstract class Callback_PropertiesAdmin_getPropertiesForPrefix
    extends IceInternal.TwowayCallback implements Ice.TwowayCallbackArg1<java.util.Map<java.lang.String, java.lang.String>>
{
    public final void __completed(Ice.AsyncResult __result)
    {
        PropertiesAdminPrxHelper.__getPropertiesForPrefix_completed(this, __result);
    }
}
