// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates connection failures.
 *
 **/
public class ConnectFailedException extends SocketException
{
    public ConnectFailedException()
    {
        super();
    }

    public ConnectFailedException(Throwable __cause)
    {
        super(__cause);
    }

    public ConnectFailedException(int error)
    {
        super(error);
    }

    public ConnectFailedException(int error, Throwable __cause)
    {
        super(error, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::ConnectFailedException";
    }

    public static final long serialVersionUID = 3367444083227777090L;
}
