// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates a lost connection.
 *
 **/
public class ConnectionLostException extends SocketException
{
    public ConnectionLostException()
    {
        super();
    }

    public ConnectionLostException(Throwable __cause)
    {
        super(__cause);
    }

    public ConnectionLostException(int error)
    {
        super(error);
    }

    public ConnectionLostException(int error, Throwable __cause)
    {
        super(error, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::ConnectionLostException";
    }

    public static final long serialVersionUID = -7871526265585148499L;
}
