// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Current.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

public final class CurrentHolder extends Ice.Holder<Current>
{
    public
    CurrentHolder()
    {
    }

    public
    CurrentHolder(Current value)
    {
        super(value);
    }
}
