// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates a malformed data encapsulation.
 *
 **/
public class EncapsulationException extends MarshalException
{
    public EncapsulationException()
    {
        super();
    }

    public EncapsulationException(Throwable __cause)
    {
        super(__cause);
    }

    public EncapsulationException(String reason)
    {
        super(reason);
    }

    public EncapsulationException(String reason, Throwable __cause)
    {
        super(reason, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::EncapsulationException";
    }

    public static final long serialVersionUID = 6924075986153135793L;
}
