// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `FacetMap.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

public final class FacetMapHolder extends Ice.Holder<java.util.Map<java.lang.String, Ice.Object>>
{
    public
    FacetMapHolder()
    {
    }

    public
    FacetMapHolder(java.util.Map<java.lang.String, Ice.Object> value)
    {
        super(value);
    }
}
