// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised if no facet with the given name exists,
 * but at least one facet with the given identity exists.
 *
 **/
public class FacetNotExistException extends RequestFailedException
{
    public FacetNotExistException()
    {
        super();
    }

    public FacetNotExistException(Throwable __cause)
    {
        super(__cause);
    }

    public FacetNotExistException(Identity id, String facet, String operation)
    {
        super(id, facet, operation);
    }

    public FacetNotExistException(Identity id, String facet, String operation, Throwable __cause)
    {
        super(id, facet, operation, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::FacetNotExistException";
    }

    public static final long serialVersionUID = -584705670010603188L;
}
