// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised if an unsupported feature is used. The
 * unsupported feature string contains the name of the unsupported
 * feature
 *
 **/
public class FeatureNotSupportedException extends Ice.LocalException
{
    public FeatureNotSupportedException()
    {
        unsupportedFeature = "";
    }

    public FeatureNotSupportedException(Throwable __cause)
    {
        super(__cause);
        unsupportedFeature = "";
    }

    public FeatureNotSupportedException(String unsupportedFeature)
    {
        this.unsupportedFeature = unsupportedFeature;
    }

    public FeatureNotSupportedException(String unsupportedFeature, Throwable __cause)
    {
        super(__cause);
        this.unsupportedFeature = unsupportedFeature;
    }

    public String
    ice_name()
    {
        return "Ice::FeatureNotSupportedException";
    }

    /**
     * The name of the unsupported feature.
     *
     **/
    public String unsupportedFeature;

    public static final long serialVersionUID = -4629958372080397318L;
}
