// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates that an attempt has been made to
 * change the connection properties of a fixed proxy.
 *
 **/
public class FixedProxyException extends Ice.LocalException
{
    public FixedProxyException()
    {
    }

    public FixedProxyException(Throwable __cause)
    {
        super(__cause);
    }

    public String
    ice_name()
    {
        return "Ice::FixedProxyException";
    }

    public static final long serialVersionUID = 3198117120780643493L;
}
