// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised when a failure occurs during initialization.
 *
 **/
public class InitializationException extends Ice.LocalException
{
    public InitializationException()
    {
        reason = "";
    }

    public InitializationException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public InitializationException(String reason)
    {
        this.reason = reason;
    }

    public InitializationException(String reason, Throwable __cause)
    {
        super(__cause);
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "Ice::InitializationException";
    }

    /**
     * The reason for the failure.
     *
     **/
    public String reason;

    public static final long serialVersionUID = 578611869232039264L;
}
