// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates that an asynchronous invocation failed
 * because it was canceled explicitly by the user using the
 * <tt>Ice::AsyncResult::cancel</tt> method.
 *
 **/
public class InvocationCanceledException extends Ice.LocalException
{
    public InvocationCanceledException()
    {
    }

    public InvocationCanceledException(Throwable __cause)
    {
        super(__cause);
    }

    public String
    ice_name()
    {
        return "Ice::InvocationCanceledException";
    }

    public static final long serialVersionUID = -6429704142271073768L;
}
