// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates that an invocation failed because it timed
 * out.
 *
 **/
public class InvocationTimeoutException extends TimeoutException
{
    public InvocationTimeoutException()
    {
        super();
    }

    public InvocationTimeoutException(Throwable __cause)
    {
        super(__cause);
    }

    public String
    ice_name()
    {
        return "Ice::InvocationTimeoutException";
    }

    public static final long serialVersionUID = -4956443780705036860L;
}
