// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised for errors during marshaling or unmarshaling data.
 *
 **/
public class MarshalException extends ProtocolException
{
    public MarshalException()
    {
        super();
    }

    public MarshalException(Throwable __cause)
    {
        super(__cause);
    }

    public MarshalException(String reason)
    {
        super(reason);
    }

    public MarshalException(String reason, Throwable __cause)
    {
        super(reason, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::MarshalException";
    }

    public static final long serialVersionUID = -1332260000897066889L;
}
