// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised if an {@link ObjectAdapter} cannot be activated.
 *
 * This happens if the {@link Locator} detects another active {@link ObjectAdapter} with
 * the same adapter id.
 *
 **/
public class ObjectAdapterIdInUseException extends Ice.LocalException
{
    public ObjectAdapterIdInUseException()
    {
        id = "";
    }

    public ObjectAdapterIdInUseException(Throwable __cause)
    {
        super(__cause);
        id = "";
    }

    public ObjectAdapterIdInUseException(String id)
    {
        this.id = id;
    }

    public ObjectAdapterIdInUseException(String id, Throwable __cause)
    {
        super(__cause);
        this.id = id;
    }

    public String
    ice_name()
    {
        return "Ice::ObjectAdapterIdInUseException";
    }

    /**
     * Adapter ID.
     *
     **/
    public String id;

    public static final long serialVersionUID = 609699148378869554L;
}
