// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised if an object does not exist on the server,
 * that is, if no facets with the given identity exist.
 *
 **/
public class ObjectNotExistException extends RequestFailedException
{
    public ObjectNotExistException()
    {
        super();
    }

    public ObjectNotExistException(Throwable __cause)
    {
        super(__cause);
    }

    public ObjectNotExistException(Identity id, String facet, String operation)
    {
        super(id, facet, operation);
    }

    public ObjectNotExistException(Identity id, String facet, String operation, Throwable __cause)
    {
        super(id, facet, operation, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::ObjectNotExistException";
    }

    public static final long serialVersionUID = 5680607485723114764L;
}
