// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `BuiltinSequences.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

public final class ObjectProxySeqHolder extends Ice.Holder<Ice.ObjectPrx[]>
{
    public
    ObjectProxySeqHolder()
    {
    }

    public
    ObjectProxySeqHolder(Ice.ObjectPrx[] value)
    {
        super(value);
    }
}
