// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates that a failure occurred while initializing
 * a plug-in.
 *
 **/
public class PluginInitializationException extends Ice.LocalException
{
    public PluginInitializationException()
    {
        reason = "";
    }

    public PluginInitializationException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public PluginInitializationException(String reason)
    {
        this.reason = reason;
    }

    public PluginInitializationException(String reason, Throwable __cause)
    {
        super(__cause);
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "Ice::PluginInitializationException";
    }

    /**
     * The reason for the failure.
     *
     **/
    public String reason;

    public static final long serialVersionUID = 1589933368626096169L;
}
