// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates socket errors.
 *
 **/
public class SocketException extends SyscallException
{
    public SocketException()
    {
        super();
    }

    public SocketException(Throwable __cause)
    {
        super(__cause);
    }

    public SocketException(int error)
    {
        super(error);
    }

    public SocketException(int error, Throwable __cause)
    {
        super(error, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::SocketException";
    }

    public static final long serialVersionUID = -7634050967564791782L;
}
