// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception is raised if a system error occurred in the server
 * or client process. There are many possible causes for such a system
 * exception. For details on the cause, {@link SyscallException#error}
 * should be inspected.
 *
 **/
public class SyscallException extends Ice.LocalException
{
    public SyscallException()
    {
        error = 0;
    }

    public SyscallException(Throwable __cause)
    {
        super(__cause);
        error = 0;
    }

    public SyscallException(int error)
    {
        this.error = error;
    }

    public SyscallException(int error, Throwable __cause)
    {
        super(__cause);
        this.error = error;
    }

    public String
    ice_name()
    {
        return "Ice::SyscallException";
    }

    /**
     * The error number describing the system exception. For C++ and
     * Unix, this is equivalent to <tt>errno</tt>. For C++
     * and Windows, this is the value returned by
     * <tt>GetLastError()</tt> or
     * <tt>WSAGetLastError()</tt>.
     *
     **/
    public int error;

    public static final long serialVersionUID = -2440066513892919497L;
}
