// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * The operation can only be invoked with a twoway request.
 *
 * This exception is raised if an attempt is made to invoke an
 * operation with <tt>ice_oneway</tt>, <tt>ice_batchOneway</tt>, <tt>ice_datagram</tt>,
 * or <tt>ice_batchDatagram</tt> and the operation has a return value,
 * out-parameters, or an exception specification.
 *
 **/
public class TwowayOnlyException extends Ice.LocalException
{
    public TwowayOnlyException()
    {
        operation = "";
    }

    public TwowayOnlyException(Throwable __cause)
    {
        super(__cause);
        operation = "";
    }

    public TwowayOnlyException(String operation)
    {
        this.operation = operation;
    }

    public TwowayOnlyException(String operation, Throwable __cause)
    {
        super(__cause);
        this.operation = operation;
    }

    public String
    ice_name()
    {
        return "Ice::TwowayOnlyException";
    }

    /**
     * The name of the operation that was invoked.
     *
     **/
    public String operation;

    public static final long serialVersionUID = -7036652448391478186L;
}
