// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Connection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Provides access to the connection details of a UDP connection
 *
 **/
public class UDPConnectionInfo extends IPConnectionInfo
{
    public UDPConnectionInfo()
    {
        super();
        mcastAddress = "";
        mcastPort = -1;
    }

    public UDPConnectionInfo(boolean incoming, String adapterName, String connectionId, int rcvSize, int sndSize, String localAddress, int localPort, String remoteAddress, int remotePort, String mcastAddress, int mcastPort)
    {
        super(incoming, adapterName, connectionId, rcvSize, sndSize, localAddress, localPort, remoteAddress, remotePort);
        this.mcastAddress = mcastAddress;
        this.mcastPort = mcastPort;
    }

    /**
     * The multicast address.
     **/
    public String mcastAddress;

    /**
     * The multicast port.
     **/
    public int mcastPort;

    public UDPConnectionInfo
    clone()
    {
        return (UDPConnectionInfo)super.clone();
    }

    public static final long serialVersionUID = -8896988970206981178L;
}
