// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates that an unknown reply status has been received.
 *
 **/
public class UnknownReplyStatusException extends ProtocolException
{
    public UnknownReplyStatusException()
    {
        super();
    }

    public UnknownReplyStatusException(Throwable __cause)
    {
        super(__cause);
    }

    public UnknownReplyStatusException(String reason)
    {
        super(reason);
    }

    public UnknownReplyStatusException(String reason, Throwable __cause)
    {
        super(reason, __cause);
    }

    public String
    ice_name()
    {
        return "Ice::UnknownReplyStatusException";
    }

    public static final long serialVersionUID = -6816121886863135119L;
}
