// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `LocalException.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * This exception indicates an unsupported data encoding version.
 *
 **/
public class UnsupportedEncodingException extends ProtocolException
{
    public UnsupportedEncodingException()
    {
        super();
        bad = new EncodingVersion();
        supported = new EncodingVersion();
    }

    public UnsupportedEncodingException(Throwable __cause)
    {
        super(__cause);
        bad = new EncodingVersion();
        supported = new EncodingVersion();
    }

    public UnsupportedEncodingException(String reason, EncodingVersion bad, EncodingVersion supported)
    {
        super(reason);
        this.bad = bad;
        this.supported = supported;
    }

    public UnsupportedEncodingException(String reason, EncodingVersion bad, EncodingVersion supported, Throwable __cause)
    {
        super(reason, __cause);
        this.bad = bad;
        this.supported = supported;
    }

    public String
    ice_name()
    {
        return "Ice::UnsupportedEncodingException";
    }

    /**
     * The version of the unsupported encoding.
     *
     **/
    public EncodingVersion bad;

    /**
     * The version of the encoding that is supported.
     *
     **/
    public EncodingVersion supported;

    public static final long serialVersionUID = -4128311673376608852L;
}
