// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Connection.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Provides access to the connection details of a WebSocket connection
 *
 **/
public class WSConnectionInfo extends TCPConnectionInfo
{
    public WSConnectionInfo()
    {
        super();
    }

    public WSConnectionInfo(boolean incoming, String adapterName, String connectionId, int rcvSize, int sndSize, String localAddress, int localPort, String remoteAddress, int remotePort, java.util.Map<java.lang.String, java.lang.String> headers)
    {
        super(incoming, adapterName, connectionId, rcvSize, sndSize, localAddress, localPort, remoteAddress, remotePort);
        this.headers = headers;
    }

    /**
     * The headers from the HTTP upgrade request.
     **/
    public java.util.Map<java.lang.String, java.lang.String> headers;

    public WSConnectionInfo
    clone()
    {
        return (WSConnectionInfo)super.clone();
    }

    public static final long serialVersionUID = 1998225894598904793L;
}
