// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Endpoint.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice;

/**
 * Provides access to a WebSocket endpoint information.
 *
 **/
public abstract class WSEndpointInfo extends TCPEndpointInfo
{
    public WSEndpointInfo()
    {
        super();
        resource = "";
    }

    public WSEndpointInfo(int timeout, boolean compress, String host, int port, String sourceAddress, String resource)
    {
        super(timeout, compress, host, port, sourceAddress);
        this.resource = resource;
    }

    /**
     * The URI configured with the endpoint.
     *
     **/
    public String resource;

    public WSEndpointInfo
    clone()
    {
        return (WSEndpointInfo)super.clone();
    }

    public static final long serialVersionUID = -5601233326414676225L;
}
