// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `ConnectionInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceSSL;

/**
 * Provides access to the connection details of an SSL connection
 *
 **/
public class ConnectionInfo extends Ice.IPConnectionInfo
{
    public ConnectionInfo()
    {
        super();
        cipher = "";
    }

    public ConnectionInfo(boolean incoming, String adapterName, String connectionId, int rcvSize, int sndSize, String localAddress, int localPort, String remoteAddress, int remotePort, String cipher, String[] certs, boolean verified)
    {
        super(incoming, adapterName, connectionId, rcvSize, sndSize, localAddress, localPort, remoteAddress, remotePort);
        this.cipher = cipher;
        this.certs = certs;
        this.verified = verified;
    }

    /**
     * The negotiated cipher suite.
     **/
    public String cipher;

    /**
     * The certificate chain.
     **/
    public String[] certs;

    /**
     * The certificate chain verification status.
     **/
    public boolean verified;

    public ConnectionInfo
    clone()
    {
        return (ConnectionInfo)super.clone();
    }

    public static final long serialVersionUID = 3176149711087722035L;
}
