// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `EndpointInfo.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceSSL;

/**
 * Provides access to an SSL endpoint information.
 *
 **/
public abstract class EndpointInfo extends Ice.IPEndpointInfo
{
    public EndpointInfo()
    {
        super();
    }

    public EndpointInfo(int timeout, boolean compress, String host, int port, String sourceAddress)
    {
        super(timeout, compress, host, port, sourceAddress);
    }

    public EndpointInfo
    clone()
    {
        return (EndpointInfo)super.clone();
    }

    public static final long serialVersionUID = 8453261032045701448L;
}
