// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Metrics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceMX;

/**
 * Get the metrics objects for the given metrics view. This
 * returns a dictionnary of metric maps for each metrics class
 * configured with the view. The timestamp allows the client to
 * compute averages which are not dependent of the invocation
 * latency for this operation.
 * 
 **/

public interface _Callback_MetricsAdmin_getMetricsView extends Ice.TwowayCallbackUE
{
    public void response(java.util.Map<java.lang.String, Metrics[]> __ret, long timestamp);
}
