// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Metrics.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceMX;

/**
 * Provides information on servant dispatch.
 *
 **/
public class DispatchMetrics extends Metrics
{
    public DispatchMetrics()
    {
        super();
        userException = 0;
        size = 0L;
        replySize = 0L;
    }

    public DispatchMetrics(String id, long total, int current, long totalLifetime, int failures, int userException, long size, long replySize)
    {
        super(id, total, current, totalLifetime, failures);
        this.userException = userException;
        this.size = size;
        this.replySize = replySize;
    }

    private static class __F implements Ice.ObjectFactory
    {
        public Ice.Object create(String type)
        {
            assert(type.equals(ice_staticId()));
            return new DispatchMetrics();
        }

        public void destroy()
        {
        }
    }
    private static Ice.ObjectFactory _factory = new __F();

    public static Ice.ObjectFactory
    ice_factory()
    {
        return _factory;
    }

    public static final String[] __ids =
    {
        "::Ice::Object",
        "::IceMX::DispatchMetrics",
        "::IceMX::Metrics"
    };

    public boolean ice_isA(String s)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public boolean ice_isA(String s, Ice.Current __current)
    {
        return java.util.Arrays.binarySearch(__ids, s) >= 0;
    }

    public String[] ice_ids()
    {
        return __ids;
    }

    public String[] ice_ids(Ice.Current __current)
    {
        return __ids;
    }

    public String ice_id()
    {
        return __ids[1];
    }

    public String ice_id(Ice.Current __current)
    {
        return __ids[1];
    }

    public static String ice_staticId()
    {
        return __ids[1];
    }

    protected void __writeImpl(IceInternal.BasicStream __os)
    {
        __os.startWriteSlice(ice_staticId(), -1, false);
        __os.writeInt(userException);
        __os.writeLong(size);
        __os.writeLong(replySize);
        __os.endWriteSlice();
        super.__writeImpl(__os);
    }

    protected void __readImpl(IceInternal.BasicStream __is)
    {
        __is.startReadSlice();
        userException = __is.readInt();
        size = __is.readLong();
        replySize = __is.readLong();
        __is.endReadSlice();
        super.__readImpl(__is);
    }

    /**
     * The number of dispatch that failed with a user exception.
     *
     **/
    public int userException;

    /**
     * The size of the dispatch. This corresponds to the size of the
     * marshalled input parameters.
     *
     **/
    public long size;

    /**
     * The size of the dispatch reply. This corresponds to the size of
     * the marshalled output and return parameters.
     *
     **/
    public long replySize;

    public DispatchMetrics
    clone()
    {
        return (DispatchMetrics)super.clone();
    }

    public static final long serialVersionUID = 8536118955902550290L;
}
