// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `IceBox.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceBox;

public class _ServiceTie implements Service, Ice.TieBase
{
    public _ServiceTie()
    {
    }

    public _ServiceTie(_ServiceOperationsNC delegate)
    {
        _ice_delegate = delegate;
    }

    public java.lang.Object ice_delegate()
    {
        return _ice_delegate;
    }

    public void ice_delegate(java.lang.Object delegate)
    {
        _ice_delegate = (_ServiceOperationsNC)delegate;
    }

    public boolean equals(java.lang.Object rhs)
    {
        if(this == rhs)
        {
            return true;
        }
        if(!(rhs instanceof _ServiceTie))
        {
            return false;
        }

        return _ice_delegate.equals(((_ServiceTie)rhs)._ice_delegate);
    }

    public int hashCode()
    {
        return _ice_delegate.hashCode();
    }

    public _ServiceTie clone()
        throws java.lang.CloneNotSupportedException
    {
        return (_ServiceTie)super.clone();
    }

    public void start(String name, Ice.Communicator communicator, String[] args)
    {
        _ice_delegate.start(name, communicator, args);
    }

    public void stop()
    {
        _ice_delegate.stop();
    }

    private _ServiceOperationsNC _ice_delegate;

    public static final long serialVersionUID = -7506042424620814118L;
}
