// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `IceBox.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceBox;

/**
 * Shut down all services. This causes {@link Service#stop} to be
 * invoked on all configured services.
 * 
 **/

public abstract class Callback_ServiceManager_shutdown extends Ice.OnewayCallback
{
}
