// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `IceBox.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package IceBox;

/**
 * This exception is a general failure notification. It is thrown
 * for errors such as a service encountering an error during
 * initialization, or the service manager being unable
 * to load a service executable.
 *
 **/
public class FailureException extends Ice.LocalException
{
    public FailureException()
    {
        reason = "";
    }

    public FailureException(Throwable __cause)
    {
        super(__cause);
        reason = "";
    }

    public FailureException(String reason)
    {
        this.reason = reason;
    }

    public FailureException(String reason, Throwable __cause)
    {
        super(__cause);
        this.reason = reason;
    }

    public String
    ice_name()
    {
        return "IceBox::FailureException";
    }

    /**
     * The reason for the failure.
     *
     **/
    public String reason;

    public static final long serialVersionUID = -7740030157337496059L;
}
