// **********************************************************************
//
// Copyright (c) 2003-2017 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.4
//
// <auto-generated>
//
// Generated from file `Instrumentation.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Ice.Instrumentation;

/**
 * The connection observer interface to instrument Ice connections.
 *
 **/
public interface _ConnectionObserverOperationsNC extends _ObserverOperationsNC
{
    /**
     * Notification of sent bytes over the connection.
     *
     * @param num The number of bytes sent.
     *
     **/
    void sentBytes(int num);

    /**
     * Notification of received bytes over the connection.
     *
     * @param num The number of bytes received.
     *
     **/
    void receivedBytes(int num);
}
