

#broker集群地址
server.address = 114.116.137.5:9092
#业务主题列表
bus.topic.list = log:test

# 日志相关
# ./kafka-topics.sh --zookeeper 114.115.151.3:2181,114.116.137.5:2181,114.115.170.155:2181 --create --topic klog_env_prod --replication-factor 3 --partitions 3